language: java
sudo: true
before_install: "./etc/travis-setup.sh"
script: ./mvnw clean install $([ -n "$HEROKU_API_KEY" ] && echo "-Pintegration-test")
deploy:
  provider: script
  script: bin/release-perform
  on:
    tags: true
    branch: master
